events {
    worker_connections 1024;
}

pid logs/sitio1.pid;

http {
    server {
        listen 81;

        location / {
            root "/mnt/c/Users/m4r14/OneDrive/Documentos/LISTILLA/DESARROLLO WEB/17289/nginx/3sitios/sitio1";
            index index.html;
        }
    }
}
